### ISSUE TITLE
Problem Of Class 12

### ISSUE THREAD

**Issue by sadiqulislam** [SabujXi/LibraryManagementSystem-Django#27]
I got This Error When I Run My Code:

'lms.Author.sex: (fields.E005) 'choices' must be an iterable containing (actual value, human readable name) tuples.'

**Comment by SabujXi** [comment]
Ah, choices should have been iterable of iterables and the inner iterables will be of length two. The elements of the inner iterable will be strings (as we are using CharField)

So, change the choices from:
```
choices=("Male", "Female", "Others")
```

To
```
choices=(
    ("Male", "Male"),
    ("Female", "Female",
    ("Others", "Others")
)
```

Alternatively we could use 
```
choices=(
    ("male", "Male"),
    ("memale", "Female",
    ("others", "Others")
)
```
But we won't do that and the reason was explained in class.
